language: c
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
install:
  - sudo apt-get install gcc-4.8
  - export CC="gcc-4.8"
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./gaussian_elimination/gaussian_elimination ../gaussian_elimination/data/data.txt
notifications:
  email:
    - reximkut@gmail.com